name: skripsi
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    cloud_firestore: ^5.5.0
    firebase_auth: ^5.3.1
    firebase_core: ^3.6.0
    firebase_storage: ^12.3.6
    camera: ^0.11.0+2
    permission_handler: ^11.3.1
    provider: ^6.1.2
    image_picker: ^1.1.2
    image: ^4.5.2
    tflite_flutter: ^0.11.0
    google_mlkit_face_detection: ^0.13.1
    shared_preferences: ^2.5.2
    flutter_map: ^8.1.0
    latlong2: ^0.9.1
    flutter_map_cancellable_tile_provider: ^3.1.0
    intl: ^0.20.2
    geolocator: ^13.0.2
    syncfusion_flutter_xlsio: ^28.2.12
    web: ^1.1.1
    http: ^1.4.0
    table_calendar: ^3.2.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - images/
        - assets/